# API配置
chat_api: "http://2.tcp.cpolar.cn:12682/v1/chat/completions"
predict_api: "http://2.tcp.cpolar.cn:12682/v1/chat/predict"
get_model: "http://2.tcp.cpolar.cn:12682/v1/models"
get_prompt_api: "http://2.tcp.cpolar.cn:12682/v1/prompts"
user_manage_api: "http://6.tcp.cpolar.cn:14287"

# 用户管理数据库，host禁止写公网ip，只能写内网ip
database:
  host: "192.168.132.149"
  port: 5437
  database: "postgres"
  username: "postgres"
  password: "postgres"

# 用户表配置
user_table:
  name: "zhida_users"

